### ISSUE TITLE
cater for js and jsx

### ISSUE THREAD

**Issue by joshua1** [mikerhyssmith/ts-barrelr#13]
How do i change the file extension regex in the settings to cater for js and jsx

**Comment by mikerhyssmith** [comment]
Does this work for you  `\\.jsx?$` ?

**Comment by joshua1** [comment]
it does, i actually did set that but would rather a ts(x) or js(x) as opposed to completely replacing ts(x)

**Comment by mikerhyssmith** [comment]
How about `\\.(js|ts)x?$` ?

**Comment by joshua1** [comment]
Thanks @mikerhyssmith that will be perfect
