### ISSUE TITLE
Add an exporer context menu

### ISSUE THREAD

**Issue by snebjorn** [mikerhyssmith/ts-barrelr#14]
It would be a nice addition to have an explorer context menu, like [this](https://marketplace.visualstudio.com/items?itemName=NG-42.ng-fortytwo-vscode-extension) extensions has.

![example](https://github.com/ng-fortytwo/vs-code-extension/raw/master/images/barrel-menu.png)

**Comment by mikerhyssmith** [comment]
Good idea ! I can get that added over this weekend 🙂

**Comment by mikerhyssmith** [comment]
A basic version of this that adds a barrel to the selected folder is out in 1.0.1 ! Let me know if you have any troubles with it 👍  !

**Comment by snebjorn** [comment]
It works :)

Cheers
