### ISSUE TITLE
Includes .tsx extension to the generated index file 

### ISSUE THREAD

**Issue by Cyrus-d** [mikerhyssmith/ts-barrelr#15]
when generating index file from .tsx files the plugin also includes the extension as follow:

export * from './Component.tsx';

and result in the following [ts] error:

An import path cannot end with a '.tsx' extension. Consider importing './Component' instead.

it doesn't do that with .ts file, so I am wondering if it intentional? if it is could you please make it optional from setting when you get a chance.

Thanks,

**Comment by mikerhyssmith** [comment]
Hi,

Thanks for opening the issue that's definitely not intentional so I'll get that fixed !

Thanks 🙂

**Comment by mikerhyssmith** [comment]
This should be fixed in 1.3.0 :-), It will now use the regex for file extensions to strip them off when the `index.ts` is produced

Let me know if that works for you !

**Comment by Cyrus-d** [comment]
Just tried the new version, it works like a charm, thank you for spending time to fix the issue, much appreciated.
