### ISSUE TITLE
EOL setting

### ISSUE THREAD

**Issue by geersch** [mikerhyssmith/ts-barrelr#22]
Currently `ts-barrelr` uses `CRLF` as the end of line marker. It would be handy if there is a configuration setting where we could change this to `LF` or any other EOL marker.

**Comment by geersch** [comment]
Apparently this is already implemented. I missed it, because this isn't on the Visual Studio code market place:

https://marketplace.visualstudio.com/items?itemName=mikerhyssmith.ts-barrelr

But it is explained here on GitHub.

**Comment by geersch** [comment]
@mikerhyssmith : Could it be that this hasn't been released yet? Looking at the history I see you added this setting 9 months ago but the latest VS Code release was in December 2018.

**Comment by mikerhyssmith** [comment]
@geersch I'm sorry for such a long delay on this! You are absolutely right, I will get this fixed now !
