### ISSUE TITLE
quote

### ISSUE THREAD

**Issue by maxisam** [mikerhyssmith/ts-barrelr#6]
According to tslints' suggestion, it should use single quote. Should we add an config file for this or just change it to use single quote ?

**Comment by mikerhyssmith** [comment]
I wasn't sure how best to achieve this, a specific config file could work but might be frustrating to require another config file. Maybe its possible to add extension specific options within vscodes own options or even better configure it using the existing tsconfig/tslint files to determine the structure and the glob of files to build into the barrel ?

**Comment by maxisam** [comment]
i think most of people would go for adding extension specific options within vscodes own options.

However, is there any reason for using double quote ? which is against TSLint ?

**Comment by mikerhyssmith** [comment]
Only because the projects I'd been working on had double quote set as the default in the tslint config ! I'm happy to make single quote the default and then use some config settings to change it if needs be ! I'll have a look at getting that sorted today !

**Comment by maxisam** [comment]
Thank you ! it is a great project !

**Comment by atticae** [comment]
I also would prefer the following:
- Make single quote the default
- Let us change the default through the VS code config

**Comment by mikerhyssmith** [comment]
Working on getting this fixed shortly !

**Comment by mikerhyssmith** [comment]
Fix for this is out now, I'm not 100% sure its the best performing solution but it should fix the problem for now !

**Comment by maxisam** [comment]
I just tried it. Somehow it doesn't work on 1.9.1.

**Comment by mikerhyssmith** [comment]
Looks like searching for the tsconfig is taking too long, I'm going to look for another approach today!

**Comment by mikerhyssmith** [comment]
Sorry for how long this has taken. Using tslint config was causing it to take far too long to produce the file and quite often not working ! Ive replaced this now wither barrelr.useDoubleQuotes as a configuration option. This should be fixed now in version 0.3.0. Let me know if it works for you !

**Comment by mikerhyssmith** [comment]
Looks like this is sorted ! Closing.
